## Session 2 - NumPy

__________________________________________________________________________

Ex. 1 : Create a NumPy array from a list of numbers and calculate the mean.

See how to use **array** and **mean** methods with numpy.

In [1]:
import numpy as np

In [13]:
# Create a NumPy array from a list of numbers
data = np.random.rand(2,3)

# Calculate the mean
mean = round(np.mean(data),2)

# Print the result
print(f"array data: {data}")
print(f"\nMean: {mean}")

array data: [[0.85403394 0.70307913 0.97582594]
 [0.31250509 0.4510581  0.5744481 ]]

Mean: 0.65


The output should look like :  
  
Mean : 3.0

__________________________________________________________________________

Ex. 2 : Create a NumPy array from a list of numbers and calculate the median.

See how to use **array** and **median** methods with numpy.

In [10]:
# Create a NumPy array from a list of numbers
data = np.random.rand(2,2)

# Calculate the median
median = round(np.median(data),2)

# Print the result
print(f"array data: {data}")
print(f"\n Median: {median}")

array data: [[0.0828986  0.8191154 ]
 [0.42348454 0.65793731]]

 Median: 0.54


The expected output is :  
  
Median : 3.0

__________________________________________________________________________

Ex. 3 : Create a NumPy array from a list of numbers and calculate the standard deviation.

See how to use **array** and **std** methods with numpy.

In [18]:
# Create a NumPy array from a list of numbers
data = np.array([[2,4,3], [1,6,2]])

# Calculate the standard deviation
std_dev = np.std(data)

# Print the result
print(f"array data: {data}")
print(f"\n Standard Deviation: {std_dev}")

array data: [[2 4 3]
 [1 6 2]]

 Standard Deviation: 1.632993161855452


The output is expected like so :  
  
Standard Deviation : 1.4142135623730951

__________________________________________________________________________

Ex. 4 : Create two NumPy arrays of the same shape and calculate the element-wise sum.

See how to use **array** and **add** methods with numpy.

In [25]:
# Create two NumPy arrays of the same shape
data1 = np.random.randint(10, size = (2,2))
data2 = np.random.randint(5, size = (2,2))

# Calculate the element-wise sum
sum = data1+data2

# Print the result
print(f"array data1: {data1}")
print(f"\n array data2: {data2}")
print(f"\n Sum: {sum}")

array data1: [[3 5]
 [9 9]]

 array data2: [[4 1]
 [4 2]]

 Sum: [[ 7  6]
 [13 11]]


The output is expected like so :

In [ ]:
#       Sum :
#        [[ 8 10 12]
#        [14 16 18]]

__________________________________________________________________________

Ex. 5 : Create two NumPy arrays of the same shape and calculate the element-wise difference.

See how to use **array** and **subtract** methods with numpy.

In [27]:
# Create two NumPy arrays of the same shape
data1 = np.random.randint(20,size=(2,3))
data2 = np.random.randint(5, size =(2,3))

# Calculate the element-wise difference
diff = data1-data2

# Print the result
print(f"array data1: {data1}")
print(f"\n array data2: {data2}")
print(f"\n Difference: {diff}")

array data1: [[ 9 17 18]
 [12 17  9]]

 array data2: [[0 1 2]
 [0 2 2]]

 Difference: [[ 9 16 16]
 [12 15  7]]


The end of the output might look like :

In [ ]:
#       Difference :
#        [[-6 -6 -6]
#        [-6 -6 -6]]